### ISSUE TITLE
Support X68000 hard disk FAT BPB

### ISSUE THREAD

**Issue by bleuge** [claunia/DiscImageChef#173]
I am looking for a tool to support HDS images for X68000 systems and emulators. 

I've read the tool support X68k DIM disk image files and Human68k (Sharp X68000) partitions table.

Tried with this example: http://nfggames.com/X68000/Games/X68000_MDX.7z 

Partition 0:
Partition name:
Partition type: Human68k
Partition start: sector 64, byte 32768
Partition length: 1843134 sectors, 943684608 bytes
Partition scheme: Human 68k partitions
Partition description:

But failed Id'ing the filesystem

Identifying filesystem on partition
Filesystem not identified

I am not an expert in these images, but found some of them. I've tried to open them with classical DiskExplorer tool  (v1.69e), but it also fails. 

If I can help in getting other examples, I can provide them.

**Comment by claunia** [comment]
HDS disk images are supported, as are HDF ones.

However Human used a different BPB for their hard disk FAT implementation whose structure currently I don't know.

Images are not a problem, what I need is documentation, technical one and/or the SDK documentation.

**Comment by IgorPetrovich** [comment]
My question next...
Need Help Or Info About HDD Format .HDS For Sharp x68000, How Open This And See For Work With This In editdisk (Disk Explorer)?
I can easy make this HDD disc with format .HDS, but can't open or i mean see in editdisk (Disk Explorer)...
With HDD ( .HDF ) it is easy working...
Before need formatting this new HDD ( .HDS ) or what? Emulators have "Logical Formating" only for .HDF, when you are just making this one new HDD ( .HDF)... But, for HDD ( .HDS ) not have option "Formatting" in emulators... 
Also i asked same in reddit, and what i already haves do at long time... Spended many to do of many time, days, but still can't get results... 😦 Downloaded many differeent emulators ( Of computer Sharp x68000 ), programs, utilities from diferent sites eng, jp, etc, was do many tests, and still fail... 
I know this is possible, because i saw in internet popular archives " X68000 " ; "X68000V4" - " X68000_V4.HDS ", with many games in it on HDD ( .HDS ) , but i want to understood and know how they got it in .HDS? 
In .HDF,  i very easy understand by time, by myself, how put, and run games on it in emulators, but main problem with .HDS, it is even can't be opened , i mean seen in editdisk (Disk Explorer)...
Any ideas or info from who know, why? And what need to do? Formatting? Which program then for it? Or what need?

**Comment by IgorPetrovich** [comment]
After time i found solved on question 1, about how make HDD ( .HDS )
All sucesfully done by this method, which i was do, and typed full information, and guide \ tutorial for someone else who also will be need this ( In future maybe or right now )...:
What i was do step by step for make HDD ( .HDS )?!
1.: Open Emulator XM6 Pro-68k or xm6_typeg_336_20230523
2.: Chose in options - Tools - Create - Fixed Disc SCSI - HDD ( .HDS ) , with sizes for tests 100 \ 1000 Mb ( In Fact 99 \ 999 Mb)
Choose Sizes ( Capacity )
Other Options:
Options Must Be On "Attached to interface." And "Replace First Drive."
Press "OK"
Checking What In Options Of Emulator, In Option SCSI - SCSI Interface - Internal - SCSI Discs ( via SCSI Interface ) - Drives ( 1 ) - ID ( 0 ) - SCSI-HD Image File ( .HDS )
3.: After created HDD ( .HDS ), i opened Emulator XM6 Pro-68k \ xm6_typeg_336_20230523 , Options - Floppy Drive #0 - MasterDisk_V3
4.: In DOS , in first i typed Command "FORMAT"
5.: Chosed "SCSI Devices" - Enter - "Hard Disc" - Enter - "Initalise" - Enter ( Y ) - "Create" - Enter - "Size"- Enter - Chosed Sizes ( 99 Mb ), by Typed this in window ( In Down Of The Screen ) - Enter -"Start" - Enter - "Create new partition" - "Y" , and got this results in end:
https://i.ibb.co/M2pdx89/44444444.png
6.: "End" - Enter.
7.: Do you want to reset? Most changes to the Partitions need it... Chosed - "Reset" ( By Press "Y" )
Done!
HDD Disc, with format .HDS - already created, formatted, can be readable now, now must be visible( In Programs \ Utilities \ In Emulators ), and ready to work ( For example in Disc Explorer ) .
P.S.:
I really like to write a lot and in detail, describing each point in detail... :)

**Comment by claunia** [comment]
@IgorPetrovich sorry we'm not understanding what are you trying to provide?

This issue has been fixed as indicated in:
@[claunia](https://github.com/claunia) closed this as [completed](https://github.com/aaru-dps/Aaru/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted) in https://github.com/aaru-dps/Aaru/commit/97073e34f02a55cb9aa368fd46d3afbee0a820ee [on Apr 9, 2018](https://github.com/aaru-dps/Aaru/issues/173#event-1564411660)

We already support and extract files from X68000 disk images, and operating system, as well as support their extended length Shift-JIS filenames, so...

Are you trying to report a new bug?

**Comment by IgorPetrovich** [comment]
Hm.
I see now.
I thinked here is was about other analogical problem...(Which also solved now)
Sorry, this all because language barrier...

**Comment by robin-francois** [comment]
Hello @IgorPetrovich,

Maybe you can talk in the language you know best and we shall use machine translation. That might be easier for everyone.
