### ISSUE TITLE
Add option to disable reading subchannel data for formats that support it

### ISSUE THREAD

**Issue by SilasLaspada** [claunia/DiscImageChef#186]
My drive doesn't seem to be able to read subchannel data consistently, when I dump a disc in Alcohol 120% with subchannel data the files have different hashes. As far as I can tell DIC always reads subchannel data if possible when dumping to MDS, but that makes it hard to compare the image files created by it versus ones created by Alcohol 120%. Would it be possible to add an option to disable reading subchannel data for formats that support it?

**Comment by claunia** [comment]
No drive is able to read subchannel data consistently, at all, because it has no error detection or protection, it just happens to have bits set and unset at will.

Compare function of DiscImageChef allows to compare two MDS images without taking the subchannel in account, or amongst different formats.

If you use a format that doesn't support subchannel (like bin/cue) with the -f option, it will be ignored.

**Comment by SilasLaspada** [comment]
Ok, I wasn't aware of the compare function so I will use that in the future. I still think it would be a useful feature to have (Alcohol 120% allows you to do this), but I won't insist on it.

**Comment by claunia** [comment]
Create a feature request using the provided issue template and I’ll add it in the future
