### ISSUE TITLE
CDs with audio tracks not matching Redump/DiscImageCreator.

### ISSUE THREAD

**Issue by RibShark** [claunia/DiscImageChef#197]
### Prerequisites

* [x] Are you running the latest version?
* [x] Can you reproduce the problem in the debug version?

### Check and fill as appropiate:
* [x] I was running DiscImageChef under Windows 10...
* [x] ...in 64-bit

### Description

When dumping (certain?) discs with audio tracks, the output does not match that of DiscImageCreator which is used by redump.org. 
### Exact command line used:

`DiscImageChef.exe  dump-media -i F: -f -o RayColl.cue`

### Expected behavior:
When using the `compare` command and comparing to a dump made by DiscImageCreator, the sectors should be identical.

### Actual behavior:
On a disc (Rayman Collector), the number of sectors in track 1 according to DiscImageCreator is 120371. DiscImageChef reports the same disc as having 120521 sectors in track 1. When running the `compare` command against the two dumps, the image is identical until sector 120371. 120371-120372 are reported as being different, 120373-120521 have different sizes (2048 bytes in DIChef, 2352 in DICreator) but are otherwise identical. All sectors from 120542 onwards are reported as being different.

In the log created by DICreator, "Skipping 512 blocks from errored block 120352." appears between reading track 1 and 2.

The dump on redump has a 2:01 pregap on track 2, which according to [redump's wiki](http://wiki.redump.org/index.php?title=Moderating_guidelines_for_IBM_PC_and_other_systems#Mastering_characteristics) means that it contains a scrambled data sector. This may well be the cause of the issue.

**Comment by claunia** [comment]
Your report is three part.

First part, 
> All sectors from 120542 onwards are reported as being different.
This is due to @saramibreak's tool applying the drive offset I don't yet do, but will do, so moved to #198 
> 120373-120521 have different sizes
They are audio sectors but as they are marked as data sectors by the TOC, that's where the size difference (and the drive read error on them) comes from. Just aesthetical, so nothing to fix there
> the number of sectors in track 1.... etc
@saramibreak's tool uses the pregap to set the track borders, I do according to the TOC, as the rainbow book says it should be done (and that's why the drive failed, as it tries to read the pregap sectors and data, they don't pass the ECC, so the drive returns error status, and trimming them the drive doesn't care because they don't have a data sync mark). Nonetheless I'll revise the rainbow books because my memory may fail :smile: and if applicable reopen the issue.
